name: qurbanqu
description: "Aplikasi tabungan qurban"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  firebase_core: ^3.10.1
  firebase_database: ^11.3.0
  firebase_auth: ^5.4.0
  shared_preferences: ^2.2.1
  intl: ^0.18.1
  provider: ^6.0.5
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Komentar dulu assets sampai Anda siap menambahkannya
  # assets:
  #   - assets/images/qurban_bg.jpg
  
  # Komentar dulu fonts sampai Anda siap menambahkannya
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600