// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJwiI4p2v_y4cpAvSzA1OpMqfNf1M_Ero',
    appId: '1:906889057538:web:463719e72afb8ca06a1e1b',
    messagingSenderId: '906889057538',
    projectId: 'qurbanqu-446b0',
    authDomain: 'qurbanqu-446b0.firebaseapp.com',
    databaseURL: 'https://qurbanqu-446b0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'qurbanqu-446b0.firebasestorage.app',
    measurementId: 'G-6STRHT20NY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfoBPYgMA-ipdP4cuZRYj7YMdURteSmxs',
    appId: '1:906889057538:android:d6a7dfece3cccc3a6a1e1b',
    messagingSenderId: '906889057538',
    projectId: 'qurbanqu-446b0',
    databaseURL: 'https://qurbanqu-446b0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'qurbanqu-446b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU7XZLrXzz79ziPGv7URrdT5P6wIwp5tE',
    appId: '1:906889057538:ios:f1aa9ff1a669695d6a1e1b',
    messagingSenderId: '906889057538',
    projectId: 'qurbanqu-446b0',
    databaseURL: 'https://qurbanqu-446b0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'qurbanqu-446b0.firebasestorage.app',
    iosBundleId: 'com.example.qurbanqu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU7XZLrXzz79ziPGv7URrdT5P6wIwp5tE',
    appId: '1:906889057538:ios:f1aa9ff1a669695d6a1e1b',
    messagingSenderId: '906889057538',
    projectId: 'qurbanqu-446b0',
    databaseURL: 'https://qurbanqu-446b0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'qurbanqu-446b0.firebasestorage.app',
    iosBundleId: 'com.example.qurbanqu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJwiI4p2v_y4cpAvSzA1OpMqfNf1M_Ero',
    appId: '1:906889057538:web:c64e51048a7a68276a1e1b',
    messagingSenderId: '906889057538',
    projectId: 'qurbanqu-446b0',
    authDomain: 'qurbanqu-446b0.firebaseapp.com',
    databaseURL: 'https://qurbanqu-446b0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'qurbanqu-446b0.firebasestorage.app',
    measurementId: 'G-7K41MEVB5P',
  );
}
